DATA_DIR :  dataset/data
MODEL_DIR : model/results
IMAGE_HEIGTH : 128
IMAGE_WIDTH : 128
IMAGE_DEEPTH : 3
TRAIN_DATA_NAME : images_manufacturer_train.txt
TEST_DATA_NAME : images_manufacturer_test.txt
TARGET_NAME : manufacturer
MODEL_NAME : epoch_100_model
EPOCH : 100